name: Ansible Playbook

on:
  push:
    branches:
      - main
  # Ermöglicht das manuelle Auslösen des Workflows
  workflow_dispatch:

jobs:
  ansible:
    name: ansible playbook
    runs-on: ubuntu-latest

    steps:
      - name: Ansible Playbook nutzen
        working-directory: ./ansible
        run: ansible-playbook -i ./inventory.ini playbook.yml
