name: Ansible files & Deployment

on:
  push:
    branches: -main
  pull_request:
    branches: -main

jobs:
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p playbooks'
